theme: minima
author: Igor Fijalkowski
description: 
# Igor Fijalkowski - Portfolio
A page where I will be uploading data projects that I have been working on.

# ${{\color{blue}Project\ 1:\ Hyrox\ Results\ Dashboard}}$

Hyrox is a sport of fitness racing. Participants sign up for the events where they have to complete 8km of running split into 8x1km and 8 stations between them. For more information, I recommend checking Hyrox's official website: www.hyrox.com

* The purpose of this project is to allow members of the gym community to view and compare their Hyrox results. The official website where participants can view the results is not the most user-friendly and does not allow you to compare results between events, you need to manually export data into Excel or on paper and compare results.
* As a result I have decided to create a dashboard in Tableau and publish it to allow all gym members to track their progress, compare results between events, and help myself and other personal trainers to spot areas for improvements for future events.
* First I had to get hold of the data. I could do it manually by creating an Excel template where I would paste the raw data, then process/clean the data, and paste it into a table (this works well for sourcing individual results).
* For larger data sets, I had to find a way to scrape the data off the website with my limited Python knowledge. I found a Python script on Kaggle that allows me to scrape the data off for specific events.
* Once data was exported, I prepared the data in Excel to be loaded into Tableau.
* Next, I have created calculated fields to display key metrics.
* Lastly I have created a basic dashboard with visualisations and filters for the gym members to view their results.

Tableau dashboard:
![Alt text](https://github.com/Igor-Fij/Portfolio/blob/main/images/Tableau%20Hyrox%20Dashboard.JPG?raw=true)

PowerBI dashboard:
![Alt text](https://github.com/Igor-Fij/Portfolio/blob/main/images/PowerBI%20Dashboard.JPG?raw=true)




